apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policybindings.monokle.io
spec:
  group: monokle.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - policyName
                - validationActions
              properties:
                policyName:
                  type: string
                validationActions:
                  type: array
                  items:
                    type: string
                    enum: [Warn, Deny]
                matchResources:
                  type: object
                  properties:
                    namespaceSelector:
                      type: object
                      properties:
                        matchLabels:
                          type: object
                          additionalProperties:
                            type: string
                        matchExpressions:
                          type: array
                          items:
                            type: object
                            required:
                              - key
                              - operator
                              - values
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                                enum: [In, NotIn]
                              values:
                                type: array
                                items:
                                  type: string
  scope: Cluster
  names:
    plural: policybindings
    singular: policybinding
    kind: MonoklePolicyBinding
    shortNames:
    - mpb
