{{- if .Values.automationToken }}
apiVersion: v1
kind: Secret
metadata:
  name: monokle-synchronizer-token
  namespace: {{ include "monokle-admission-controller.namespace" . }}
type: Opaque
data:
  .token: {{ .Values.automationToken | b64enc | quote }}
{{- end }}
