{{- if .Values.automationToken }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monokle-policies-synchronizer-sa
  namespace: {{ include "monokle-admission-controller.namespace" . }}
  labels:
    {{- include "monokle-admission-controller.labels" . | nindent 4 }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-synchronizer-cluster
  labels:
    {{- include "monokle-admission-controller.labels" . | nindent 4 }}
rules:
- apiGroups: ["monokle.io"]
  resources: ["policies", "policybindings"]
  verbs: ["create", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-synchronizer-cluster
  labels:
    {{- include "monokle-admission-controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: monokle-policies-synchronizer-sa
  namespace: {{ include "monokle-admission-controller.namespace" . }}
roleRef:
  kind: ClusterRole
  name: monokle-policies-synchronizer-cluster
  apiGroup: rbac.authorization.k8s.io
{{- end }}
