apiVersion: v1
kind: ServiceAccount
metadata:
  name: monokle-policies-sa
  namespace: {{ include "monokle-admission-controller.namespace" . }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies
rules:
- apiGroups: ["monokle.io"]
  resources: ["policies", "policybindings"]
  verbs: ["list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies
subjects:
- kind: ServiceAccount
  name: monokle-policies-sa
  namespace: {{ include "monokle-admission-controller.namespace" . }}
roleRef:
  kind: ClusterRole
  name: monokle-policies
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-init-vwc
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-init-vwc
subjects:
- kind: ServiceAccount
  name: monokle-policies-sa
  namespace: {{ include "monokle-admission-controller.namespace" . }}
roleRef:
  kind: ClusterRole
  name: monokle-policies-init-vwc
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-init-secrets
  namespace: {{ include "monokle-admission-controller.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-init-secrets
  namespace: {{ include "monokle-admission-controller.namespace" . }}
subjects:
- kind: ServiceAccount
  name: monokle-policies-sa
  namespace: {{ include "monokle-admission-controller.namespace" . }}
roleRef:
  kind: Role
  name: monokle-policies-init-secrets
  apiGroup: rbac.authorization.k8s.io
