apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: monokle-admission-controller-webhook
  labels:
    {{- include "monokle-admission-controller.labels" . | nindent 4 }}
webhooks:
  - name: monokle-admission-controller-server.{{ include "monokle-admission-controller.namespace" . }}.svc
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: monokle-admission-controller-server
        namespace: {{ include "monokle-admission-controller.namespace" . }}
        path: "/validate"
      caBundle: ""
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-node-lease
            - kube-public
            - kube-system
            - {{ include "monokle-admission-controller.namespace" . }}
            {{- with .Values.ignoreNamespaces }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps", "batch", "", "autoscaling", "networking.k8s.io"]
        apiVersions: ["*"]
        resources:
          - deployments
          - daemonsets
          - statefulsets
          - cronjobs
          - jobs
          - pods
          - services
          - configmaps
          - secrets
          - services
          - persistentvolumeclaims
          - ingresses
        scope: "Namespaced"
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["rbac.authorization.k8s.io", ""]
        apiVersions: ["*"]
        resources:
          - serviceaccounts
          - roles
          - rolebindings
          - clusterroles
          - clusterrolebindings
        scope: "*"
