apiVersion: monokle.io/v1alpha1
kind: MonoklePolicyBinding
metadata:
  name: policy-binding-sample-4
spec:
  policyName: "policy-sample-1"
  validationActions: [Warn]
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: In
          values:
            - nstest1
            - nstest2