apiVersion: monokle.io/v1alpha1
kind: MonoklePolicyBinding
metadata:
  name: policy-binding-sample-5
spec:
  policyName: "policy-sample-1"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: In
          values:
            - default