apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: monokle-admission-controller-server
build:
  artifacts:
    - image: admission-webhook
      context: ./admission-controller/server
      docker:
        dockerfile: ./admission-controller/server/Dockerfile
    - image: admission-webhook-init
      context: ./admission-controller/init
      docker:
        dockerfile: ./admission-controller/init/Dockerfile
    - image: admission-synchronizer
      context: ./admission-controller/synchronizer
      docker:
        dockerfile: ./admission-controller/synchronizer/Dockerfile
manifests:
  rawYaml:
    - ./scripts/install.yaml
portForward:
  - resourceType: service
    resourceName: monokle-admission-controller-server
    port: 443
