apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: monokle-admission-controller
  labels:
    app: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: server
        image: admission-webhook
        ports:
        - containerPort: 8443
          name: webhook-api
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /run/secrets/tls
          readOnly: true
        env:
          - name: MONOKLE_LOG_LEVEL
            value: DEBUG
          - name: MONOKLE_IGNORE_NAMESPACES
            value: 'kube-node-lease,kube-public,kube-system,monokle-admission-controller'
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: root-secret
      serviceAccountName: monokle-policies
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: monokle-admission-controller
spec:
  selector:
    app: webhook-server
  ports:
    - port: 443
      targetPort: webhook-api