apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policybindings.monokle.com
spec:
  group: monokle.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                policyName:
                  type: string
                validationActions:
                  type: string
                  enum: [Warn]
  scope: Cluster
  names:
    plural: policybindings
    singular: policybinding
    kind: MonoklePolicyBinding
    shortNames:
    - mpb