apiVersion: v1
kind: ServiceAccount
metadata:
  name: monokle-policies-sa
  namespace: monokle-admission-controller

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies
rules:
- apiGroups: ["monokle.io"]
  resources: ["policies", "policybindings"]
  verbs: ["list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies
subjects:
- kind: ServiceAccount
  name: monokle-policies-sa
  namespace: monokle-admission-controller
roleRef:
  kind: ClusterRole
  name: monokle-policies
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-init-vwc
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-init-vwc
subjects:
- kind: ServiceAccount
  name: monokle-policies-sa
  namespace: monokle-admission-controller
roleRef:
  kind: ClusterRole
  name: monokle-policies-init-vwc
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-init-secrets
  namespace: monokle-admission-controller
rules:
- apiGroups: ["*"] # should be "" as this is a core group
  resources: ["secrets"]
  verbs: ["get", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies-init-secrets
  namespace: monokle-admission-controller
subjects:
- kind: ServiceAccount
  name: monokle-policies-sa
  namespace: monokle-admission-controller
roleRef:
  kind: Role
  name: monokle-policies-init-secrets
  apiGroup: rbac.authorization.k8s.io
