apiVersion: v1
kind: ServiceAccount
metadata:
  name: monokle-policies
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies
rules:
- apiGroups: ["monokle.com"]
  resources: ["policies", "policybindings"]
  verbs: ["list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monokle-policies
subjects:
- kind: ServiceAccount
  name: monokle-policies
  namespace: monokle-admission-controller
roleRef:
  kind: ClusterRole
  name: monokle-policies
  apiGroup: rbac.authorization.k8s.io