image:
  init:
    repository: docker.io/kubeshop/monokle-admission-controller-init
    pullPolicy: IfNotPresent
    # Override the image tag whose default is the chart appVersion.
    tag: ""
    # Override entire image path.
    overridePath: ""
  server:
    repository: docker.io/kubeshop/monokle-admission-controller-server
    pullPolicy: IfNotPresent
    # Override the image tag whose default is the chart appVersion.
    tag: ""
    # Override entire image path.
    overridePath: ""
  synchronizer:
    repository: docker.io/kubeshop/monokle-admission-controller-synchronizer
    pullPolicy: IfNotPresent
    # Override the image tag whose default is the chart appVersion.
    tag: ""
    # Override entire image path.
    overridePath: ""

replicas: 1

# Do not validate resources from below namespaces.
ignoreNamespaces:
#   - ns1
#   - ns2

logLevel: WARN

automationToken: ""

cloudApiUrl: ""
