image:
  init:
    repository: monokle-admission-controller-init
    pullPolicy: IfNotPresent
    # Override the image tag whose default is the chart appVersion.
    tag: ""
    # Override entire image path.
    overridePath: ""
  server:
    repository: monokle-admission-controller-server
    pullPolicy: IfNotPresent
    # Override the image tag whose default is the chart appVersion.
    tag: ""
    # Override entire image path.
    overridePath: ""

# Deploy Monokle Admission Controller resources to below namespace.
namespace: monokle-admission-controller

# Do not validate resources from below namespaces.
ignoreNamespaces:
#   - ns1
#   - ns2
