# image:
#   init:
#     # repository: nginx
#     pullPolicy: IfNotPresent
#     # Overrides the image tag whose default is the chart appVersion.
#     tag: ""
#     overridePath: ''
#   server:
#     # repository: nginx
#     pullPolicy: IfNotPresent
#     # Overrides the image tag whose default is the chart appVersion.
#     tag: ""
#     overridePath: ''

# Deploy Monokle Admission Controller resources to below namespace.
namespace: monokle-admission-controller

# # Do not validate resources from these namespaces.
# ignoreNamespaces:
#   - ns1
