name: Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Skaffold
        run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Start Minikube
        run: minikube start --uuid 00000000-0000-0000-0000-000000000001 --extra-config=apiserver.enable-admission-plugins=ValidatingAdmissionWebhook

      - name: Deploy Admission Controller
        run: ./scripts/deploy.sh

      - name: Install Dependencies
        working-directory: ./tests/
        run: npm ci

      - name: Test
        working-directory: ./tests/
        run: npm test
